platform :ios, '9.0'

use_frameworks! :linkage => :dynamic
supports_swift_versions '>= 4.2' #, '< 4.0'
#warn_for_unused_master_specs_repo 'false'

target 'HBSwiftKit_Example' do
  pod 'HBSwiftKit', :path => '../'
  
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'R.swift', '~> 5.3.1'
  
  target 'HBSwiftKit_Tests' do
    inherit! :search_paths

    pod 'Quick'#, '~> 1.2.0'
    pod 'Nimble'#, '~> 7.0'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
  
#  post_install do |installer|
#      installer.pods_project.targets.each do |target|
#          target.build_configurations.each do |config|
#              config.build_settings['SWIFT_VERSION'] = '5.0'
#          end
#      end
#  end
  
end
