platform :ios, '9.0'

use_frameworks! :linkage => :dynamic
supports_swift_versions '>= 5.0' #, '< 4.0'
#warn_for_unused_master_specs_repo 'false'

target 'HBSwiftKit_Example' do
  pod 'HBSwiftKit', :path => '../'
  
  pod 'Kingfisher'
  target 'HBSwiftKit_Tests' do
    inherit! :search_paths

#    pod 'Quick', '~> 1.2.0'
#    pod 'Nimble', '~> 7.0'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
