platform :ios, '10.0'

# cdn服务器最近常挂,暂时禁用cdn分发方式; https://github.com/CocoaPods/CocoaPods/issues/11370
# CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs
#source 'source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks! #:linkage => :dynamic
#supports_swift_versions '>= 4.2' #, '< 4.0'
#warn_for_unused_master_specs_repo 'false'
#忽略引入库的所有警告
inhibit_all_warnings!

target 'HBSwiftKit_Example' do
  pod 'HBSwiftKit', :path => '../'
  
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'R.swift' #, '~> 5.3.1'
  pod 'ObjectMapper'
  pod 'Moya' #, '~> 15.0.0'
  pod 'PromiseKit' #, '~> 6.8.0'
  #pod 'OpenCV', '~> 4.3.0'
  pod 'CocoaLumberjack/Swift'
  pod 'Charts'
  pod 'Toast-Swift'
  pod 'SVProgressHUD'
  pod 'GDPerformanceView-Swift', :configurations => ['Debug']
  pod 'SwiftLint', :configurations => ['Debug']
  pod 'FLEX', :configurations => ['Debug']

  target 'HBSwiftKit_Tests' do
    inherit! :search_paths

    pod 'Quick'#, '~> 1.2.0'
    #Nimble Library not found for -libswiftXCTest https://github.com/Quick/Nimble/issues/855
    pod 'Nimble', '~> 9.2.1'
    #    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '5.0'
              #config.build_settings['COMPILER_INDEX_STORE_ENABLE'] = "NO" # OCLint配置
          end
      end
  end

end
