//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var image: image { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.image` struct is generated, and contains static references to 47 images, and 1 namespaces.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `ib_back`.
    var ib_back: RswiftResources.ImageResource { .init(name: "ib_back", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ib_delete`.
    var ib_delete: RswiftResources.ImageResource { .init(name: "ib_delete", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ib_remove`.
    var ib_remove: RswiftResources.ImageResource { .init(name: "ib_remove", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ib_select`.
    var ib_select: RswiftResources.ImageResource { .init(name: "ib_select", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ib_share`.
    var ib_share: RswiftResources.ImageResource { .init(name: "ib_share", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ib_unselect`.
    var ib_unselect: RswiftResources.ImageResource { .init(name: "ib_unselect", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_audio_tool_last`.
    var icon_audio_tool_last: RswiftResources.ImageResource { .init(name: "icon_audio_tool_last", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_audio_tool_next`.
    var icon_audio_tool_next: RswiftResources.ImageResource { .init(name: "icon_audio_tool_next", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_audio_tool_play`.
    var icon_audio_tool_play: RswiftResources.ImageResource { .init(name: "icon_audio_tool_play", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_audio_tool_stop`.
    var icon_audio_tool_stop: RswiftResources.ImageResource { .init(name: "icon_audio_tool_stop", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_audio_tool_wait`.
    var icon_audio_tool_wait: RswiftResources.ImageResource { .init(name: "icon_audio_tool_wait", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_calendar_arrow_down`.
    var icon_calendar_arrow_down: RswiftResources.ImageResource { .init(name: "icon_calendar_arrow_down", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_pause_white`.
    var icon_pause_white: RswiftResources.ImageResource { .init(name: "icon_pause_white", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_play_next_white`.
    var icon_play_next_white: RswiftResources.ImageResource { .init(name: "icon_play_next_white", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_play_white`.
    var icon_play_white: RswiftResources.ImageResource { .init(name: "icon_play_white", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `image`.
    var image: RswiftResources.ImageResource { .init(name: "image", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `last_month_enabled`.
    var last_month_enabled: RswiftResources.ImageResource { .init(name: "last_month_enabled", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `last_month_normal`.
    var last_month_normal: RswiftResources.ImageResource { .init(name: "last_month_normal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `loading.gif`.
    var loadingGif: RswiftResources.ImageResource { .init(name: "loading.gif", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `logger`.
    var logger: RswiftResources.ImageResource { .init(name: "logger", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `next_month_enabled`.
    var next_month_enabled: RswiftResources.ImageResource { .init(name: "next_month_enabled", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `next_month_normal`.
    var next_month_normal: RswiftResources.ImageResource { .init(name: "next_month_normal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pause`.
    var pause: RswiftResources.ImageResource { .init(name: "pause", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `play`.
    var play: RswiftResources.ImageResource { .init(name: "play", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `podcast.jpg`.
    var podcastJpg: RswiftResources.ImageResource { .init(name: "podcast.jpg", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `redWarning`.
    var redWarning: RswiftResources.ImageResource { .init(name: "redWarning", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ring_max`.
    var ring_max: RswiftResources.ImageResource { .init(name: "ring_max", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ring_mid`.
    var ring_mid: RswiftResources.ImageResource { .init(name: "ring_mid", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ring_min`.
    var ring_min: RswiftResources.ImageResource { .init(name: "ring_min", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `signalplate`.
    var signalplate: RswiftResources.ImageResource { .init(name: "signalplate", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `signalpointer`.
    var signalpointer: RswiftResources.ImageResource { .init(name: "signalpointer", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `star_nomal`.
    var star_nomal: RswiftResources.ImageResource { .init(name: "star_nomal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `star_select`.
    var star_select: RswiftResources.ImageResource { .init(name: "star_select", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sw_ang_bottom`.
    var sw_ang_bottom: RswiftResources.ImageResource { .init(name: "sw_ang_bottom", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sw_ang_left`.
    var sw_ang_left: RswiftResources.ImageResource { .init(name: "sw_ang_left", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sw_ang_right`.
    var sw_ang_right: RswiftResources.ImageResource { .init(name: "sw_ang_right", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sw_ang_top`.
    var sw_ang_top: RswiftResources.ImageResource { .init(name: "sw_ang_top", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sw_panel_bottom`.
    var sw_panel_bottom: RswiftResources.ImageResource { .init(name: "sw_panel_bottom", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sw_panel_left`.
    var sw_panel_left: RswiftResources.ImageResource { .init(name: "sw_panel_left", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sw_panel_normal`.
    var sw_panel_normal: RswiftResources.ImageResource { .init(name: "sw_panel_normal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sw_panel_ok`.
    var sw_panel_ok: RswiftResources.ImageResource { .init(name: "sw_panel_ok", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sw_panel_right`.
    var sw_panel_right: RswiftResources.ImageResource { .init(name: "sw_panel_right", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sw_panel_top`.
    var sw_panel_top: RswiftResources.ImageResource { .init(name: "sw_panel_top", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `swift`.
    var swift: RswiftResources.ImageResource { .init(name: "swift", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `topHintbg`.
    var topHintbg: RswiftResources.ImageResource { .init(name: "topHintbg", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `yellow_arrow`.
    var yellow_arrow: RswiftResources.ImageResource { .init(name: "yellow_arrow", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `椭圆形备份 2`.
    var 椭圆形备份2: RswiftResources.ImageResource { .init(name: "椭圆形备份 2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
    var tabBar: tabBar { .init(bundle: bundle) }

    func tabBar(bundle: Foundation.Bundle) -> tabBar {
      .init(bundle: bundle)
    }


    /// This `_R.image.tabBar` struct is generated, and contains static references to 6 tabBars.
    struct tabBar {
      let bundle: Foundation.Bundle

      /// Image `TabBar/home_h`.
      var home_h: RswiftResources.ImageResource { .init(name: "TabBar/home_h", path: ["TabBar"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `TabBar/home_n`.
      var home_n: RswiftResources.ImageResource { .init(name: "TabBar/home_n", path: ["TabBar"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `TabBar/like_h`.
      var like_h: RswiftResources.ImageResource { .init(name: "TabBar/like_h", path: ["TabBar"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `TabBar/like_n`.
      var like_n: RswiftResources.ImageResource { .init(name: "TabBar/like_n", path: ["TabBar"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `TabBar/web_h`.
      var web_h: RswiftResources.ImageResource { .init(name: "TabBar/web_h", path: ["TabBar"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `TabBar/web_n`.
      var web_n: RswiftResources.ImageResource { .init(name: "TabBar/web_n", path: ["TabBar"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 26 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `.env.default`.
    var envDefault: RswiftResources.FileResource { .init(name: ".env", pathExtension: "default", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Appfile`.
    var appfile: RswiftResources.FileResource { .init(name: "Appfile", pathExtension: "", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Fastfile`.
    var fastfile: RswiftResources.FileResource { .init(name: "Fastfile", pathExtension: "", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `MediaAssets.bundle`.
    var mediaAssetsBundle: RswiftResources.FileResource { .init(name: "MediaAssets", pathExtension: "bundle", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Pluginfile`.
    var pluginfile: RswiftResources.FileResource { .init(name: "Pluginfile", pathExtension: "", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `README.md`.
    var readmeMd: RswiftResources.FileResource { .init(name: "README", pathExtension: "md", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `advfilterdata.json`.
    var advfilterdataJson: RswiftResources.FileResource { .init(name: "advfilterdata", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `areacode.plist`.
    var areacodePlist: RswiftResources.FileResource { .init(name: "areacode", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `duallist.json`.
    var duallistJson: RswiftResources.FileResource { .init(name: "duallist", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `help_cn.html`.
    var help_cnHtml: RswiftResources.FileResource { .init(name: "help_cn", pathExtension: "html", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `help_es.html`.
    var help_esHtml: RswiftResources.FileResource { .init(name: "help_es", pathExtension: "html", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `images.json`.
    var imagesJson: RswiftResources.FileResource { .init(name: "images", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `jstest.html`.
    var jstestHtml: RswiftResources.FileResource { .init(name: "jstest", pathExtension: "html", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `loading.gif`.
    var loadingGif: RswiftResources.FileResource { .init(name: "loading", pathExtension: "gif", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `percentage.json`.
    var percentageJson: RswiftResources.FileResource { .init(name: "percentage", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `podcast.jpg`.
    var podcastJpg: RswiftResources.FileResource { .init(name: "podcast", pathExtension: "jpg", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `report.xml`.
    var reportXml: RswiftResources.FileResource { .init(name: "report", pathExtension: "xml", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `src_hsv`.
    var src_hsv: RswiftResources.FileResource { .init(name: "src_hsv", pathExtension: "", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `src_temp`.
    var src_temp: RswiftResources.FileResource { .init(name: "src_temp", pathExtension: "", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `src_xy`.
    var src_xy: RswiftResources.FileResource { .init(name: "src_xy", pathExtension: "", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `五音Jw-明月天涯.mp3`.
    var 五音Jw明月天涯Mp3: RswiftResources.FileResource { .init(name: "五音Jw-明月天涯", pathExtension: "mp3", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `友情的决裂.mp4`.
    var 友情的决裂Mp4: RswiftResources.FileResource { .init(name: "友情的决裂", pathExtension: "mp4", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `友情的决裂intro.mp4`.
    var 友情的决裂introMp4: RswiftResources.FileResource { .init(name: "友情的决裂intro", pathExtension: "mp4", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `李荣浩 - 老街.mp3`.
    var 李荣浩老街Mp3: RswiftResources.FileResource { .init(name: "李荣浩 - 老街", pathExtension: "mp3", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `温柔女声.mp3`.
    var 温柔女声Mp3: RswiftResources.FileResource { .init(name: "温柔女声", pathExtension: "mp3", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `萧忆情Alex - 不谓侠.mp3`.
    var 萧忆情Alex不谓侠Mp3: RswiftResources.FileResource { .init(name: "萧忆情Alex - 不谓侠", pathExtension: "mp3", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }
    var main: main { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func main(bundle: Foundation.Bundle) -> main {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
      try self.main.validate()
    }


    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {

      }
    }

    /// Storyboard `Main`.
    struct main: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = ViewController

      let bundle: Foundation.Bundle

      let name = "Main"
      func validate() throws {

      }
    }
  }
}